### ISSUE TITLE
打算添加greasyfork的插件检测代码到项目内, 并在点击脚本安装按钮时执行检测

### ISSUE THREAD

**Issue by mengzonefire** [XTsat/rapid-upload-userscript-doc#1]
如题, 占个坑, 具体效果如下:
![Snipaste_2022-06-09_04-11-43](https://user-images.githubusercontent.com/44224240/172708422-bb774db1-04bd-4e2f-93eb-b23bd786a1f1.png)

**Comment by mengzonefire** [comment]
反复看了下源码, gf能检测油猴和暴力猴插件的安装状态仅仅是因为 这两个插件会在gf页面的window.external内插入标记, 而在其他的页面不插入, 故无法实现自行检测

失望 (

**Comment by XTsat** [comment]
不能自己插入检测吗？

- 我看了几个
  - https://blog.csdn.net/atudz82862/article/details/101394798
  - https://www.lmlphp.com/user/151597/article/item/3510102/

也许tampermonkey有一个声明接口

**Comment by mengzonefire** [comment]
GM_info这个接口只能在运行的油猴脚本内使用

目前看来除了插件主动暴露标记, 没有其他黑科技检测方法, 在暴力猴源码中可以看到, 插件仅在gf暴露标记:

[options-defaults.js -> line17](https://github.com/violentmonkey/violentmonkey/blob/master/src/common/options-defaults.js)

**Comment by XTsat** [comment]
就是因为脚本不是全网页运行所以没法检测特征码啊，不然直接检查脚本特征就行了，网页应该可以检测有没有脚本管理器吧

**Comment by XTsat** [comment]
是这些脚本管理器只给了gf白名单吗？

**Comment by mengzonefire** [comment]
> 是这些脚本管理器只给了gf白名单吗？

sodayo (

![Snipaste_2022-06-10_00-58-09](https://user-images.githubusercontent.com/44224240/172902847-b5d45b0c-c5a3-4800-8ed2-d2ee801e0c53.png)

**Comment by XTsat** [comment]
需要检测的主要问题在于没安装脚本的人打开一键秒传链接会进入百度网盘主页，要不然改成浏览器不解析的链接必须有秒传才能进的链接

不然这个问题只能让网站主反复提示[discussions/136085](https://greasyfork.org/zh-CN/scripts/424574-%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96/discussions/136085)

**Comment by XTsat** [comment]
但是这又需要全局运行脚本

**Comment by mengzonefire** [comment]
> 但是这又需要全局运行脚本

未安装插件的情况下, 只能在跳转百度的源站点进行提示, 没有别的更好办法了

**Comment by XTsat** [comment]
> > 但是这又需要全局运行脚本
> 
> 未安装插件的情况下, 只能在跳转百度的源站点进行提示, 没有别的更好办法了

知道安装脚本的不会有问题，不知道安装脚本的就算出一个全局检测的也不会安装，确实只有提示这一个方法
