### ISSUE TITLE
{"errno":9019,"errmsg":"need verify",

### ISSUE THREAD

**Issue by nilfunc** [XTsat/rapid-upload-userscript-doc#2]

**Comment by XTsat** [comment]
是不是发错地方了，这里仅为文档的仓库，脚本仓库在https://github.com/mengzonefire/rapid-upload-userscript/issues?q=is%3Aissue
脚本地址在https://greasyfork.org/zh-CN/scripts/424574-%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96/feedback

**Comment by wodty** [comment]
failed link: failed get link: 200 OK; {"errno":9019,"errmsg":"needverify","request_id":302939307475802725};
直接点开报错
下载报错{"code":500,"message":"failed link: failed get link:  200 OK; {\"errno\":9019,\"errmsg\":\"needverify\",\"request_id\":302951524843266136}; ","data":null}有大佬知道什么问题么

**Comment by XTsat** [comment]
[由于外部原因，项目永久停止维护，各位另请高明吧](https://github.com/mengzonefire/rapid-upload-userscript/issues/38)
