### ISSUE TITLE
如何在云端生成秒传链接

### ISSUE THREAD

**Issue by liaosunny123** [XTsat/rapid-upload-userscript-doc#3]
在文档中的示例以及网页网站中只有本地文件计算秒传链接，怎么计算网盘中的云端文件的秒传链接？

**Comment by XTsat** [comment]
脚本本身是计算网盘中的秒传链接
至于网页端确实只能生成本地秒传
纯本地计算需要额外下载软件
[秒传链接生成方式](https://xtsat.github.io/rapid-upload-userscript-doc/document/%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E7%94%9F%E6%88%90/%E7%A7%92%E4%BC%A0%E7%94%9F%E6%88%90%E7%9B%B8%E5%85%B3.html)

**Comment by liaosunny123** [comment]
方便的话可以说一下脚本计算网盘中的秒传链接的原理是什么吗？是利用百度网盘现有的API还是需要自己处理诶。想知道如何不用脚本实现计算网盘中文件的秒传链接

**Comment by XTsat** [comment]
这有一个作者做的从分享链接创建秒传的脚本[23.3.24: **提供一个简易的分享链生成秒传的后端](https://github.com/mengzonefire/shareLink2bdLink)**
具体提取的代码我不了解，但是原理是利用百度网盘自带的闪传功能，相同md5值视为同一文件，只要百度服务器中有就能通过脚本实现本地伪上传文件，类似生成百度md5的工具有许多
不用脚本也要用类似的带此功能的第三方客户端才行（或许你想自己做个第三方客户端？）
@mengzonefire

**Comment by mengzonefire** [comment]
"想知道如何不用脚本实现计算网盘中文件的秒传链接" -> [BaiduPCS-Go 导出文件目录](https://github.com/qjfoidnh/BaiduPCS-Go#%E5%AF%BC%E5%87%BA%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95)
```
# 导出 /我的资源 格式为通用秒传链接格式
BaiduPCS-Go export /我的资源 --link
```

**Comment by mengzonefire** [comment]
“可以说一下脚本计算网盘中的秒传链接的原理是什么吗”
->

<img width="613" alt="Snipaste_2023-04-24_19-27-27" src="https://user-images.githubusercontent.com/44224240/233983317-f95846c6-e935-453a-89bb-3be23d825e0c.png">

**Comment by liaosunny123** [comment]
感谢，了解了！
