### ISSUE TITLE
求助秒传未生效(请看文档:载点1 载点2)(#404) 

### ISSUE THREAD

**Issue by 0000070** [XTsat/rapid-upload-userscript-doc#4]
任何文件都是生成失败，https://pic.imgdb.cn/item/647e8c741ddac507cc10389e.png

点击载点里面的链接提示：**请求的脚本已被删除。**

这个脚本不更新了？咋搞啊

**Comment by mengzonefire** [comment]
咋搞？不用了呗

**Comment by XTsat** [comment]
> 任何文件都是生成失败，https://pic.imgdb.cn/item/647e8c741ddac507cc10389e.png
> 
> 点击载点里面的链接提示：**请求的脚本已被删除。**
> 
> 这个脚本不更新了？咋搞啊

脚本已停止维护
[由于外部原因，项目永久停止维护](https://github.com/mengzonefire/rapid-upload-userscript#readme)
